spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: root
  jpa:
    hibernate:
      hbm2ddl:
        auto: none
      dialect: org.hibernate.dialect.PostgreSQL82Dialect

flyway:
  enabled: true
