spring:
  datasource:
    tomcat:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
house:
  openapi:
    dev-url: http://localhost:8080
springdoc:
  swagger-ui:
    path: /documentation
    try-it-out-enabled: true
  api-docs:
    path: /api-doc
  packages-to-scan: by.clevertec.house.controller
cache:
  algorithm: lfu
  max-collection-size: 100
